@@ -0,0 +1,14 @@
version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ShortUrlDomain=\"www.urlcutlabs.site\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
